# This file is only for local development
version: '3.7'

services:
  app:
    build: .
    command: >
        uvicorn app.main:sio_app
        --host 0.0.0.0 --port 8000
        --reload
        --reload-dir /app
        --reload-include *.html
        --reload-include *.js
        --reload-include *.css
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      WATCHFILES_FORCE_POLLING: true
